### ISSUE TITLE
disqus

### ISSUE THREAD

**Issue by jackvial** [nodeschool/cleveland#13]
Add disqus to the site for coments

**Comment by kmckee** [comment]
Could we use github issues for this instead?  Looks like that's what some of the other chapters are doing.

**Comment by jackvial** [comment]
Using the issues would be more straight forward and save having to create a disqus account for anyone who doesn't have one already. Displaying them on the page using the github api with a link the the relevant issue/comment thread would be nice feature too. Are any of the other chapters using the api to display the comments/issues?

**Comment by yaworsw** [comment]
There is only 1 page on the Cleveland site + we haven't had an event yet.  Is there any necessity to having a place for folks to talk about it?  I'd say meetup.com already covers that.

**Comment by kmckee** [comment]
Good point.  I looked into this a little more and it looks like nodeschool actually recommends keeping the website pretty lean and recommends using issues for the bulk of the content (https://github.com/nodeschool/organizers/wiki).  I think we should go with that for now and reconsider if we find a need in the future.  thanks guys
